---
- name: Disable booting into the GUI
  ansible.builtin.file: 
    src: /lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Upgrade the dist
  ansible.builtin.apt:
    upgrade: dist

- name: Upgrade the packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    autoclean: true
    autoremove: true

- name: Reboot host and wait for it to restart
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

